attack:
  pgd_order: before
bab:
  attack:
    enabled: false
  batched_domain_list: true
  branching:
    method: babsr
    reduceop: max
  get_upper_bound: false
  max_domains: 50000
data:
  dataset: CIFAR
general:
  complete_verifier: bab
  device: cpu
  enable_incomplete_verification: false
solver:
  batch_size: 1000
  beta-crown:
    beta: true
  bound_prop_method: alpha-crown
