attack:
  pgd_order: skip
bab:
  branching:
    method: fsb
    reduceop: max
  max_domains: 100000
data:
  dataset: CIFAR
general:
  complete_verifier: bab
  device: cpu
  enable_incomplete_verification: true
solver:
  beta-crown:
    batch_size: 200
    beta: true
