attack:
  pgd_order: before
bab:
  attack:
    enabled: false
  batched_domain_list: false
  branching:
    method: fsb
    reduceop: max
  get_upper_bound: false
  max_domains: 100000
data:
  dataset: MNIST
general:
  complete_verifier: bab
  device: cuda
  enable_incomplete_verification: true
solver:
  batch_size: 50
  beta-crown:
    beta: true
  bound_prop_method: alpha-crown
