attack:
  pgd_order: before
bab:
  attack:
    enabled: false
  batched_domain_list: false
  branching:
    method: babsr
    reduceop: max
  get_upper_bound: false
  max_domains: 50000
data:
  dataset: CIFAR
general:
  complete_verifier: bab
  device: cuda
  enable_incomplete_verification: false
model:
  onnx_loader: Customized("custom_model_loader", "customized_Marabou_loader")
solver:
  batch_size: 200
  beta-crown:
    beta: false
  bound_prop_method: alpha-crown
