attack:
  pgd_order: skip
bab:
  branching:
    method: kfsb
    reduceop: max
  max_domains: 100000
data:
  dataset: dave_gvdb
general:
  complete_verifier: bab
  device: cpu
  enable_incomplete_verification: true
solver:
  beta-crown:
    batch_size: 1
    beta: true
