attack:
  pgd_order: skip
bab:
  attack:
    enabled: false
  batched_domain_list: false
  branching:
    method: sb
    reduceop: max
  get_upper_bound: false
  max_domains: 60000
data:
  dataset: vnncomp21
general:
  complete_verifier: bab
  device: cuda
  enable_incomplete_verification: false
solver:
  batch_size: 200
  bound_prop_method: alpha-crown
